# name: Deploy to AKS Cluster
# on:
#   push:
#     branches:
#     - master

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@master
    
#     - uses: Azure/docker-login@v1
#       with:
#         login-server: cloudlifeacr.azurecr.io
#         username: ${{ secrets.AZURE_USERNAME }}
#         password: ${{ secrets.AZURE_PASSWORD }}
    
#     - run: |
#         docker build . -t cloudlifeacr.azurecr.io/eidodata:${{ github.sha }}
#         docker push cloudlifeacr.azurecr.io/eidodata:${{ github.sha }}
      
#     # Set the target AKS cluster.
#     - uses: Azure/aks-set-context@v1
#       with:
#         creds: '${{ secrets.AZURE_CREDENTIALS }}'
#         cluster-name: azure-k8s
#         resource-group: AKS-Cluster-RG
        
#     - uses: Azure/k8s-create-secret@v1
#       with:
#         container-registry-url: cloudlifeacr.azurecr.io
#         container-registry-username: ${{ secrets.AZURE_USERNAME }}
#         container-registry-password: ${{ secrets.AZURE_PASSWORD }}
#         secret-name: k8s-secret

#     - uses: Azure/k8s-deploy@v1
#       with: 
#         manifests:
#           deployment.yaml

#         images: |
#           cloudlifeacr.azurecr.io/eidodata:${{ github.sha }}
#         imagepullsecrets: |
#           k8s-secret